// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Fp1itixt2L7ub2ThG_OIqbypaTaaAxQ',
    appId: '1:653734660965:web:f41023fc454812a56b2f8c',
    messagingSenderId: '653734660965',
    projectId: 'chatapp-930cf',
    authDomain: 'chatapp-930cf.firebaseapp.com',
    storageBucket: 'chatapp-930cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9o7e0epiYbV8bBOQf6CqW5ExwiyoBaM',
    appId: '1:653734660965:android:bc656b9cdad42b7f6b2f8c',
    messagingSenderId: '653734660965',
    projectId: 'chatapp-930cf',
    storageBucket: 'chatapp-930cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAASKAgO7uVJNjcEb3pPltSCFNKeAIlE1A',
    appId: '1:653734660965:ios:5226a313a4b002ea6b2f8c',
    messagingSenderId: '653734660965',
    projectId: 'chatapp-930cf',
    storageBucket: 'chatapp-930cf.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAASKAgO7uVJNjcEb3pPltSCFNKeAIlE1A',
    appId: '1:653734660965:ios:5226a313a4b002ea6b2f8c',
    messagingSenderId: '653734660965',
    projectId: 'chatapp-930cf',
    storageBucket: 'chatapp-930cf.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Fp1itixt2L7ub2ThG_OIqbypaTaaAxQ',
    appId: '1:653734660965:web:2302932909f78b076b2f8c',
    messagingSenderId: '653734660965',
    projectId: 'chatapp-930cf',
    authDomain: 'chatapp-930cf.firebaseapp.com',
    storageBucket: 'chatapp-930cf.appspot.com',
  );
}
